name: cicd

on:
  push:
    tags:
      - '**'

jobs:
  example:
    run: echo ${GITHUB_REF#refs/*/}
  # build:
  #   uses: jsonxr/actions/.github/workflows/npm-cicd.yml@main
  # publish:
  #   needs: build
  #   uses: jsonxr/actions/.github/workflows/npm-publish.yml@main
  #   with:
  #     version: ${GITHUB_REF#refs/*/}
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
